services:
  postgres:
    image: bitnami/postgresql:15
    networks:
      - app_net
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: chat
      POSTGRESQL_PGAUDIT_LOG: none
    volumes:
      - postgres-data:/bitnami/postgresql
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d chat" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped


  frontend-chat:
    build: 
      context: ./Frontend
      target: development
    networks:
      - app_net
    depends_on:
      chat:
        condition: service_started 
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_END=development
      - VITE_HOST=0.0.0.0
    restart: unless-stopped

  chat:
    build: ./Backend
    networks:
      - app_net
    environment:
      ConnectionStrings__PostgreSQL: "Host=postgres;Port=5433;Database=chat;Username=postgres;Password=postgres;Timeout=300"
      ConnectionStrings__Redis: "redis"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

  redis:
    image: docker.io/bitnami/redis:7.0
    networks:
      - app_net
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/bitnami/redis/data
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
